apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
        resource: hello
    spec:
      containers:
      - name: hello-world
        image: eu.gcr.io/cpy-docker-test/hello-world
        env:
        - name: HELLO_BIND_PORT
          value: "8080"
#        - name: AUTH_SECRET
#          valueFrom:
#            secretKeyRef:
#              name: k8s_auth_secret
#              key: token
        - name: AUTH_SECRET
          value: "secret"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world-service
    resource: hello
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world